In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

data_laptop = {
    "Brand": ["ASUS", "HP", "LENOVO", "APPLE", "ACER"],
    "CPU": [
        "Core i5-13500H",
        "Reyzen 5 7530U",
        "Core i7-14700HX",
        "M2-Pro",
        "Core i3-N305",
    ],
    "RAM": ["16GB", "8GB", "32GB", "16GB", "8GB"],
    "Storage": ["512GB SSD", "512GB SSD", "1TB SSD", "512GB SSD", "512GB SSD"],
    "Price": ["11JT", "8JT", "25JT", "21JT", "5.5JT"],
}

df_laptop = pd.DataFrame(data_laptop)
df_laptop.head()

    Brand              CPU   RAM    Storage  Price
0    ASUS   Core i5-13500H  16GB  512GB SSD   11JT
1      HP   Reyzen 5 7530U   8GB  512GB SSD    8JT
2  LENOVO  Core i7-14700HX  32GB    1TB SSD   25JT
3   APPLE           M2-Pro  16GB  512GB SSD   21JT
4    ACER     Core i3-N305   8GB  512GB SSD  5.5JT

**PEMERIKSAAN DATA AWAL**

* Shape seberapa banyak kolom dan baris
* Info memeriksa type data
* Data statistik secara keseluruhan

In [3]:
df_laptop.shape

(5, 5)

In [6]:
df_laptop.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    5 non-null      str
 1   CPU      5 non-null      str
 2   RAM      5 non-null      str
 3   Storage  5 non-null      str
 4   Price    5 non-null      str
dtypes: str(5)
memory usage: 332.0 bytes

In [8]:
df_laptop.describe(include="all")

       Brand             CPU   RAM    Storage Price
count      5               5     5          5     5
unique     5               5     3          2     5
top     ASUS  Core i5-13500H  16GB  512GB SSD  11JT
freq       1               1     2          4     1

**ANALISA PERUBAHAN KOLOM RELEVAN**

* Perubahan string ke float
* Penambahan kolom baru
* Penambahan kolom analisis (Kategori Harga)

In [9]:
# Menghapus "JT" dan mengubah tipe data menjadi float
df_laptop["Harga (Juta)"] = df_laptop["Price"].str.replace("JT", "").astype(float)

In [10]:
# Penambahan kolom baru
df_laptop["Tanggal Data"] = datetime.now().strftime("%Y-%m-%d")
df_laptop["Diskon (%)"] = 10
df_laptop["Harga Final (Juta)"] = df_laptop["Harga (Juta)"] - (
    df_laptop["Harga (Juta)"] * df_laptop["Diskon (%)"] / 100
)

In [11]:
# Penambahan kolom analisis
def tentukan_kategori(harga):
    if harga >= 20:
        return "Premium"
    elif harga >= 10:
        return "Menengah"
    else:
        return "Terjangkau"


df_laptop["Kategori Produk"] = df_laptop["Harga Final (Juta)"].apply(tentukan_kategori)

In [12]:
print("\n===== 2.Data Laptop Setelah Transformasi =====")
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
print(
    df_laptop[
        [
            "Brand",
            "CPU",
            "RAM",
            "Storage",
            "Harga (Juta)",
            "Diskon (%)",
            "Harga Final (Juta)",
            "Kategori Produk",
        ]
    ]
)

===== 2.Data Laptop Setelah Transformasi =====
    Brand              CPU   RAM    Storage  Harga (Juta)  Diskon (%)  Harga Final (Juta) Kategori Produk
0    ASUS   Core i5-13500H  16GB  512GB SSD          11.0          10                9.90      Terjangkau
1      HP   Reyzen 5 7530U   8GB  512GB SSD           8.0          10                7.20      Terjangkau
2  LENOVO  Core i7-14700HX  32GB    1TB SSD          25.0          10               22.50         Premium
3   APPLE           M2-Pro  16GB  512GB SSD          21.0          10               18.90        Menengah
4    ACER     Core i3-N305   8GB  512GB SSD           5.5          10                4.95      Terjangkau