In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("latihan4.csv")
df = pd.DataFrame(data)

In [3]:
df.head()

,Usia,Pendapatan_Bulanan,Status_Pekerjaan,Lama_Bekerja,Status_Pernikahan,Jumlah_Tanggungan,Skor_Kredit,Riwayat_Kredit,Kelayakan_Kredit
0,NaN,NaN,Kontrak,NaN,BELUM,0.0,NaN,cukup,Layak
1,NaN,10.4,NaN,18.0,Belum Menikah,9.0,542.0,NaN,layak
2,22.0,NaN,tetap,NaN,Menikah,NaN,NaN,NaN,layak
3,NaN,16.7,Kontrak,6.0,menikah,3.0,589.0,BURUK,layak
4,NaN,4.2,NaN,NaN,NaN,1.0,232.0,baik,layak

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Usia                211 non-null    float64
 1   Pendapatan_Bulanan  216 non-null    float64
 2   Status_Pekerjaan    289 non-null    str
 3   Lama_Bekerja        215 non-null    float64
 4   Status_Pernikahan   262 non-null    str
 5   Jumlah_Tanggungan   226 non-null    float64
 6   Skor_Kredit         206 non-null    float64
 7   Riwayat_Kredit      286 non-null    str
 8   Kelayakan_Kredit    258 non-null    str
dtypes: float64(5), str(4)
memory usage: 23.6 KB

In [5]:
df.describe(include="all")

,Usia,Pendapatan_Bulanan,Status_Pekerjaan,Lama_Bekerja,Status_Pernikahan,Jumlah_Tanggungan,Skor_Kredit,Riwayat_Kredit,Kelayakan_Kredit
count,211.000000,216.000000,289,215.000000,262,226.000000,206.000000,286,258
unique,NaN,NaN,7,NaN,4,NaN,NaN,6,4
top,NaN,NaN,KONTRAK,NaN,menikah,NaN,NaN,baik,layak
freq,NaN,NaN,46,NaN,71,NaN,NaN,52,70
mean,42.184834,10.617593,NaN,12.920930,NaN,5.097345,620.082524,NaN,NaN
std,12.783507,6.276902,NaN,8.747137,NaN,3.282180,174.361575,NaN,NaN
min,18.000000,1.000000,NaN,0.000000,NaN,0.000000,204.000000,NaN,NaN
25%,31.500000,5.900000,NaN,5.000000,NaN,2.000000,481.000000,NaN,NaN
50%,42.000000,9.500000,NaN,12.000000,NaN,5.000000,649.000000,NaN,NaN
75%,52.000000,13.950000,NaN,19.000000,NaN,8.000000,762.750000,NaN,NaN
max,69.000000,24.900000,NaN,35.000000,NaN,10.000000,950.000000,NaN,NaN

In [6]:
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

Usia                  123
Pendapatan_Bulanan    118
Status_Pekerjaan       45
Lama_Bekerja          119
Status_Pernikahan      72
Jumlah_Tanggungan     108
Skor_Kredit           128
Riwayat_Kredit         48
Kelayakan_Kredit       76
dtype: int64

In [7]:
# mengisi data kosong

df["Usia"] = df["Usia"].fillna(df["Usia"].mean())

df["Pendapatan_Bulanan"] = df["Pendapatan_Bulanan"].fillna(
    df["Pendapatan_Bulanan"].mean()
)

df["Status_Pekerjaan"] = df["Status_Pekerjaan"].fillna(df["Status_Pekerjaan"].mode()[0])

df["Lama_Bekerja"] = df["Lama_Bekerja"].fillna(df["Lama_Bekerja"].mode()[0])

df["Status_Pernikahan"] = df["Status_Pernikahan"].fillna(
    df["Status_Pernikahan"].mode()[0]
)

df["Jumlah_Tanggungan"] = df["Jumlah_Tanggungan"].fillna(
    df["Jumlah_Tanggungan"].mode()[0]
)

df["Skor_Kredit"] = df["Skor_Kredit"].fillna(df["Skor_Kredit"].mean())

df["Riwayat_Kredit"] = df["Riwayat_Kredit"].fillna(df["Riwayat_Kredit"].mode()[0])

df["Kelayakan_Kredit"] = df["Kelayakan_Kredit"].fillna(df["Kelayakan_Kredit"].mode()[0])

In [8]:
df.isnull().sum()

Usia                  0
Pendapatan_Bulanan    0
Status_Pekerjaan      0
Lama_Bekerja          0
Status_Pernikahan     0
Jumlah_Tanggungan     0
Skor_Kredit           0
Riwayat_Kredit        0
Kelayakan_Kredit      0
dtype: int64

In [9]:
df.head()

,Usia,Pendapatan_Bulanan,Status_Pekerjaan,Lama_Bekerja,Status_Pernikahan,Jumlah_Tanggungan,Skor_Kredit,Riwayat_Kredit,Kelayakan_Kredit
0,42.184834,10.617593,Kontrak,12.0,BELUM,0.0,620.082524,cukup,Layak
1,42.184834,10.400000,KONTRAK,18.0,Belum Menikah,9.0,542.000000,Buruk,layak
2,22.000000,10.617593,tetap,12.0,Menikah,9.0,620.082524,Buruk,layak
3,42.184834,16.700000,Kontrak,6.0,menikah,3.0,589.000000,BURUK,layak
4,42.184834,4.200000,KONTRAK,12.0,menikah,1.0,232.000000,baik,layak

In [10]:
df["Status_Pekerjaan"] = df["Status_Pekerjaan"].str.title()

df["Status_Pernikahan"] = df["Status_Pernikahan"].str.title()

df["Riwayat_Kredit"] = df["Riwayat_Kredit"].str.title()

df.head()

,Usia,Pendapatan_Bulanan,Status_Pekerjaan,Lama_Bekerja,Status_Pernikahan,Jumlah_Tanggungan,Skor_Kredit,Riwayat_Kredit,Kelayakan_Kredit
0,42.184834,10.617593,Kontrak,12.0,Belum,0.0,620.082524,Cukup,Layak
1,42.184834,10.400000,Kontrak,18.0,Belum Menikah,9.0,542.000000,Buruk,layak
2,22.000000,10.617593,Tetap,12.0,Menikah,9.0,620.082524,Buruk,layak
3,42.184834,16.700000,Kontrak,6.0,Menikah,3.0,589.000000,Buruk,layak
4,42.184834,4.200000,Kontrak,12.0,Menikah,1.0,232.000000,Baik,layak

In [11]:
Q1 = df["Pendapatan_Bulanan"].quantile(0.25)
Q3 = df["Pendapatan_Bulanan"].quantile(0.75)
IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR
lower_bound = Q1 - 1.5 * IQR

outliers = df[
    (df["Pendapatan_Bulanan"] < lower_bound) | (df["Pendapatan_Bulanan"] > upper_bound)
]

In [12]:
Q1 = df["Skor_Kredit"].quantile(0.25)
Q3 = df["Skor_Kredit"].quantile(0.75)
IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR
lower_bound = Q1 - 1.5 * IQR

outliers = df[(df["Skor_Kredit"] < lower_bound) | (df["Skor_Kredit"] > upper_bound)]

In [13]:
df["Status_Pekerjaan"].unique()

<StringArray>
['Kontrak', 'Tetap', 'Tidak Tetap', 'Wirausaha', 'Wiraswasta']
Length: 5, dtype: str

In [14]:
df["Status_Pernikahan"].unique()

<StringArray>
['Belum', 'Belum Menikah', 'Menikah']
Length: 3, dtype: str

In [15]:
df["Riwayat_Kredit"].unique()

<StringArray>
['Cukup', 'Buruk', 'Baik']
Length: 3, dtype: str

In [16]:
df["Kelayakan_Kredit"].unique()

<StringArray>
['Layak', 'layak', 'TIDAK', 'Tidak']
Length: 4, dtype: str

In [17]:
df["Kelayakan_Kredit"] = df["Kelayakan_Kredit"].replace("layak", "Layak")
df["Kelayakan_Kredit"] = df["Kelayakan_Kredit"].replace("TIDAK", "Tidak")

In [18]:
df["Kelayakan_Kredit"].unique()

<StringArray>
['Layak', 'Tidak']
Length: 2, dtype: str

In [19]:
from sklearn.tree import DecisionTreeClassifier

df_encoded = df.copy()

df_encoded["Status_Pekerjaan"] = df_encoded["Status_Pekerjaan"].map(
    {"Wirausaha": 4, "Tetap": 3, "Wiraswasta": 2, "Kontrak": 1, "Tidak Tetap": 0}
)

df_encoded["Status_Pernikahan"] = df_encoded["Status_Pernikahan"].map(
    {"Menikah": 2, "Belum Menikah": 1, "Belum": 0}
)

df_encoded["Riwayat_Kredit"] = df_encoded["Riwayat_Kredit"].map(
    {"Baik": 2, "Cukup": 1, "Buruk": 0}
)

df_encoded["Kelayakan_Kredit"] = df_encoded["Kelayakan_Kredit"].map(
    {"Layak": 1, "Tidak": 0}
)

df_encoded

,Usia,Pendapatan_Bulanan,Status_Pekerjaan,Lama_Bekerja,Status_Pernikahan,Jumlah_Tanggungan,Skor_Kredit,Riwayat_Kredit,Kelayakan_Kredit
0,42.184834,10.617593,1,12.0,0,0.0,620.082524,1,1
1,42.184834,10.400000,1,18.0,1,9.0,542.000000,0,1
2,22.000000,10.617593,3,12.0,2,9.0,620.082524,0,1
3,42.184834,16.700000,1,6.0,2,3.0,589.000000,0,1
4,42.184834,4.200000,1,12.0,2,1.0,232.000000,2,1
...,...,...,...,...,...,...,...,...,...
329,66.000000,6.200000,1,27.0,2,8.0,704.000000,0,1
330,42.184834,10.617593,2,14.0,1,5.0,787.000000,2,1
331,36.000000,13.300000,1,19.0,0,0.0,778.000000,1,1
332,65.000000,9.100000,3,12.0,2,6.0,620.082524,0,1
333,50.000000,10.617593,1,1.0,0,9.0,301.000000,2,1

In [20]:
x = df_encoded[
    [
        "Usia",
        "Pendapatan_Bulanan",
        "Status_Pekerjaan",
        "Lama_Bekerja",
        "Status_Pernikahan",
        "Jumlah_Tanggungan",
        "Skor_Kredit",
        "Riwayat_Kredit",
    ]
]
y = df_encoded["Kelayakan_Kredit"]

In [21]:
model = DecisionTreeClassifier()
model.fit(x, y)

DecisionTreeClassifier()

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

y_pred = model.predict(x_test)
cleaned_accuracy = accuracy_score(y_test, y_pred)
print("Akurasi setelah pembersihan data:", cleaned_accuracy)

Akurasi setelah pembersihan data: 1.0

In [23]:
# new data
new_data = pd.DataFrame(
    {
        "Usia": [30, 45],
        "Pendapatan_Bulanan": [5000, 8000],
        "Status_Pekerjaan": [3, 4],
        "Lama_Bekerja": [5, 10],
        "Status_Pernikahan": [1, 2],
        "Jumlah_Tanggungan": [2, 3],
        "Skor_Kredit": [700, 750],
        "Riwayat_Kredit": [2, 1],
    }
)

result = model.predict(new_data)

if result[0] == 1:
    print("Data 1: Layak")
else:
    print("Data 1: Tidak Layak")

if result[1] == 1:
    print("Data 2: Layak")
else:
    print("Data 2: Tidak Layak")

Data 1: Layak
Data 2: Layak